
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExcedeCapacidadException", targetNamespace = "http://servidor/")
public class ExcedeCapacidadException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExcedeCapacidadException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExcedeCapacidadException_Exception(String message, ExcedeCapacidadException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExcedeCapacidadException_Exception(String message, ExcedeCapacidadException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.ExcedeCapacidadException
     */
    public ExcedeCapacidadException getFaultInfo() {
        return faultInfo;
    }

}
