
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioSinSeguidosException", targetNamespace = "http://servidor/")
public class UsuarioSinSeguidosException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioSinSeguidosException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioSinSeguidosException_Exception(String message, UsuarioSinSeguidosException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioSinSeguidosException_Exception(String message, UsuarioSinSeguidosException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.UsuarioSinSeguidosException
     */
    public UsuarioSinSeguidosException getFaultInfo() {
        return faultInfo;
    }

}
