
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExisteProveedorException", targetNamespace = "http://servidor/")
public class NoExisteProveedorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExisteProveedorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExisteProveedorException_Exception(String message, NoExisteProveedorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExisteProveedorException_Exception(String message, NoExisteProveedorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.NoExisteProveedorException
     */
    public NoExisteProveedorException getFaultInfo() {
        return faultInfo;
    }

}
