
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoHaySalidasDisponiblesException", targetNamespace = "http://servidor/")
public class NoHaySalidasDisponiblesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoHaySalidasDisponiblesException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoHaySalidasDisponiblesException_Exception(String message, NoHaySalidasDisponiblesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoHaySalidasDisponiblesException_Exception(String message, NoHaySalidasDisponiblesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.NoHaySalidasDisponiblesException
     */
    public NoHaySalidasDisponiblesException getFaultInfo() {
        return faultInfo;
    }

}
